config/routes.rb
Rails.application.routes.draw do

  resources :diagnoses
  resources :reservations
  resources :blocks
  resources :treatments
  root 'welcome#index'
  devise_for :admins, path: 'admins', controllers: {sessions: "admins/sessions", registrations: "admins/registrations", confirmations: "admins/confirmations",  mailer:"admins/mailer", passwords: "admins/passwords", shared: "admins/shared", unlocks: "admins/unlocks"}
  devise_for :doctors, path: 'doctors', controllers: {sessions: "doctors/sessions", registrations:"doctors/registrations", confirmations: "doctors/confirmations", mailer: "doctors/mailer", passwords: "doctors/passwords", shared: "doctors/shared", unlocks: "doctors/unlocks"}
  devise_for :clients, path: 'clients', controllers: {sessions: "clients/sessions", registrations:"clients/registrations", confirmations: "clients/confirmations", mailer: "clients/mailer", passwords: "clients/passwords", shared: "clients/shared", unlocks: "clients/unlocks"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/pick_date' => 'reservations#pick_date'
  get '/pick_date_to_edit' => 'reservations#pick_date_to_edit'

  get '/client' => 'clients#mostrar'
  get '/client/history' => 'clients#history'
  post 'reservations/go_new'
  get '/doctor' => 'doctors#mostrar'
  
  get '/treatments/show' => 'treatments#show'
  get '/treatments/client' => 'treatments#client'
  get '/showclient' => 'treatments#showclient'

  get '/reservations_to_edit' => 'reservations#index_to_edit'
  post '/reservations_go_edit' => 'reservations#go_edit'
  get '/reservations_admin_edit' => 'reservations#admin_edit'

  get '/admin/new_doctor' => 'admins#new_doctor'
  post 'admins/add_doc'
  get '/doctor/history' => 'doctors#history'



end

app/models/treatment.rb
class Treatment < ApplicationRecord

    belongs_to :client
    belongs_to :doctor

end

app/controllers/treatments_controller.rb
class TreatmentsController < ApplicationController


  # GET /treatments
  def index
    @doctor = current_doctor
    @treatments_client_ids =  Reservation.where('doctor_id = ?', @doctor).pluck(:client_id)
    @clients = Client.where('id IN (?)', @treatments_client_ids)


  end

  def showclient
    @client = current_client
    @treatmentscomments_ids = Treatment.where('client_id = ?', @client).pluck(:doctor_id)
    @doctorscomments = Doctor.where('id IN (?)', @treatmentscomments_ids)
    @treatmentscomments = Treatment.where('client_id = ?', @client)
  end

  def client
    @client = current_client
    @doctors = Doctor.all
    @treatmentscomments = Treatment.where('client_id = ?', @client)
  end

  def show
    @treatment = Treatment.new
    @client = Client.find(params[:client])
    @doctor = Doctor.find(params[:doctor])
    @treatmentscomments = Treatment.where('client_id = ? and doctor_id = ?', @client, @doctor)

  end

  # GET /treatments/new
  def new
    @treatment = Treatment.new
    @client = Client.find(params[:client])
    @doctor = current_doctor
  end

  # GET /diagnoses/1/edit
  def edit

  end

  # POST /treatments
  def create
    @treatment = Treatment.new
    @client = params['treatment']['client_id']
    @doctor = params['treatment']['doctor_id']
    @treatment.comment = params['treatment']['comment']
    @treatment.doctor_id = @doctor
    @treatment.client_id = @client

    if @treatment.save
      redirect_to treatments_show_path(:client => @client, :doctor => @doctor), notice: 'Treatment comment was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /treatment/1
  def update
    if @treatment.update(treatment_params)
      redirect_to @treatment, notice: 'Treatment was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /treatment/1
  def destroy
    @treatment.destroy
    redirect_to treatment_url, notice: 'Treatment was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_treatment
      @treatment = Treatment.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def treatment_params
      params.require(:treatment).permit(:comment, :client_id, :doctor_id)
    end
end

app/views/treatments/_form.html.erb
<%= form_with(model: @treatment, local: true) do |form| %>
  <% if @treatment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@treatment.errors.count, "error") %> prohibited this treatment from being saved:</h2>

      <ul>
      <% @treatment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% form.label :comment %><br />
    <%= form.text_area :comment %>
  </div>

  <%= form.hidden_field :client_id, value: @client.id%>
  <%= form.hidden_field :doctor_id, value: @doctor.id%>

  <div class="actions">
    <%= form.submit "Nuevo Comentario", class: "btn btn-outline-primary" %>
  </div>
<% end %>

app/views/treatments/edit.html.erb
<h1>Editing Treatment Comment</h1>

<%= render 'form', treatment: @treatment %>

<%= link_to 'Show', @treatment %> |
<%= link_to 'Back', treatments_path %>

app/views/treatments/index.html.erb
<p id="notice"><%= notice %></p>

<center><h1>Clientes en Tratamientos con usted, Dr. <%= @doctor.first_name %> <%= @doctor.last_name %></h1>
<hr>
<table class="list-group center" style="margin-left:40%;">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
      <tr class="list-group-item d-flex justify-content-between align-items-center" style="width:30%;">
          <td><p><%= client.first_name %> <%= client.last_name %></td>
          <td><%= link_to 'Ver', treatments_show_path(:client => client.id, :doctor => @doctor.id), class: "btn btn-outline-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table></center>

<br>

<center><%= link_to 'Back', root_path, class: "btn btn-outline-primary" %></center>

app/views/treatments/new.html.erb
<h1>New Treatment Comment</h1>

<%= render 'form', treatment: @treatment %>

<%= link_to 'Back', treatments_path %>

app/views/treatments/show.html.erb
<center><h1>Tratamiento del cliente <%= @client.first_name %> <%= @client.last_name %></h1>
<hr>
<% @treatmentscomments.each do |comment| %>
    <tr>
        <td><p><%= comment.created_at.to_s[0, 20] %>: <%= comment.comment %></td>
    </tr>
<% end %>
<hr>
<%= render 'form', treatment: @treatment %>
<%= link_to 'Back', treatments_path, class: "btn btn-outline-primary" %></center>

app/views/treatments/showclient.html.erb
<p id="notice"><%= notice %></p>

<center>
<h1>Tus Tratamientos</h1>
<% @doctorscomments.each do |doctor|%>
    <h2>Tratamiento con el Dr. <%= doctor.first_name %> <%= doctor.last_name %><h2>
    <hr>
    <% @treatmentscomments.each do |comment| %>
        <% if doctor.id == comment.doctor_id %>
            <p><%= comment.created_at.to_s[0, 20] %>: <%= comment.comment %></p>
        <% end %>
    <%end%>
    <hr>
<% end %>
<%= link_to 'Back', root_path, class: "btn btn-outline-primary"  %></center>