config/routes.rb
Rails.application.routes.draw do

  resources :diagnoses
  resources :reservations
  resources :blocks
  resources :treatments
  root 'welcome#index'
  devise_for :admins, path: 'admins', controllers: {sessions: "admins/sessions", registrations: "admins/registrations", confirmations: "admins/confirmations",  mailer:"admins/mailer", passwords: "admins/passwords", shared: "admins/shared", unlocks: "admins/unlocks"}
  devise_for :doctors, path: 'doctors', controllers: {sessions: "doctors/sessions", registrations:"doctors/registrations", confirmations: "doctors/confirmations", mailer: "doctors/mailer", passwords: "doctors/passwords", shared: "doctors/shared", unlocks: "doctors/unlocks"}
  devise_for :clients, path: 'clients', controllers: {sessions: "clients/sessions", registrations:"clients/registrations", confirmations: "clients/confirmations", mailer: "clients/mailer", passwords: "clients/passwords", shared: "clients/shared", unlocks: "clients/unlocks"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/pick_date' => 'reservations#pick_date'
  get '/pick_date_to_edit' => 'reservations#pick_date_to_edit'

  get '/client' => 'clients#mostrar'
  get '/client/history' => 'clients#history'
  post 'reservations/go_new'
  get '/doctor' => 'doctors#mostrar'
  
  get '/treatments/show' => 'treatments#show'
  get '/treatments/client' => 'treatments#client'
  get '/showclient' => 'treatments#showclient'

  get '/reservations_to_edit' => 'reservations#index_to_edit'
  post '/reservations_go_edit' => 'reservations#go_edit'
  get '/reservations_admin_edit' => 'reservations#admin_edit'

  get '/admin/new_doctor' => 'admins#new_doctor'
  post 'admins/add_doc'
  get '/doctor/history' => 'doctors#history'



end

app/models/block.rb
class Block < ApplicationRecord
  has_one :reservation
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
  before_action :set_block, only: [:show, :edit, :update, :destroy]

  # GET /blocks
  def index
    @blocks = Block.all
  end

  # GET /blocks/1
  def show
  end

  # GET /blocks/new
  def new
    @block = Block.new
    @client = current_client
    @doctors = Doctor.all
  end

  # GET /blocks/1/edit
  def edit
  end

  # POST /blocks
  def create
    @block = Block.new(block_params)

    if @block.save
      redirect_to @block, notice: 'Block was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /blocks/1
  def update
    if @block.update(block_params)
      redirect_to @block, notice: 'Block was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /blocks/1
  def destroy
    @block.destroy
    redirect_to blocks_url, notice: 'Block was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_block
      @block = Block.find(params[:id])
    end
    # Only allow a trusted parameter "white list" through.
    def block_params
      params.require(:block).permit(:date, :description)
    end
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/views/blocks/_form.html.erb
<%= form_with(model: block, local: true) do |form| %>
  <% if block.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(block.errors.count, "error") %> prohibited this block from being saved:</h2>

      <ul>
      <% block.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %><br />
    <%= form.datetime_field :date, autofocus: true, autocomplete: "date" %>
  </div>

  <div class="field">
    <%= form.label :description %><br />
    <%= form.text_field :description, autofocus: true, autocomplete: "description" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blocks/edit.html.erb
<h1>Editing Block</h1>

<%= render 'form', block: @block %>

<%= link_to 'Show', @block %> |
<%= link_to 'Back', blocks_path %>

app/views/blocks/index.html.erb
<h1>Blocks</h1>
<div class="container">
  <h2>Bloques Disponibles</h2>
  <p>En la siguiente tabla se muestran las horas disponibles</p>   
  <%= link_to 'New Block', new_block_path %>  
  <br></br>         
  <table class="table table-bordered">
  <thead>
    <tr>
      <th> Descripción </th>
      <th> Fecha </th>
      <th colspan="4"></th>
    </tr>
  </thead>
    <tbody>
    <% @blocks.each do |block| %>
      <tr>
        <td><%= block.description %></td>
        <td><%= block.date %></td>
        <td><%= link_to 'Reservar', new_reservation_path(:block => block) %></td>
        <td><%= link_to 'Show', block %></td>
        <td><%= link_to 'Edit', edit_block_path(block) %></td>
        <td><%= link_to 'Destroy', block, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
</div>

app/views/blocks/new.html.erb
<h1>New Block</h1>

<%= render 'form', block: @block %>

<%= link_to 'Back', blocks_path %>

app/views/blocks/show.html.erb
<%= link_to 'Edit', edit_block_path(@block) %> |
<%= link_to 'Back', blocks_path %>
<center>
<div class="card" style="width:400px">
  <img class="card-img-top" src="https://image.freepik.com/vector-gratis/ilustracion-clinica-doctor_1270-69.jpg" alt="Card image">
  <div class="card-body">
    <h4 class="card-title"><%=@block.date%></h4>
    <p class="card-text"><%=@block.description%></p>
    <%= link_to 'Reservar', new_reservation_path(:block => @block)%>
  </div>
</div>
</center>