config/routes.rb
Rails.application.routes.draw do

  resources :diagnoses
  resources :reservations
  resources :blocks
  resources :treatments
  root 'welcome#index'
  devise_for :admins, path: 'admins', controllers: {sessions: "admins/sessions", registrations: "admins/registrations", confirmations: "admins/confirmations",  mailer:"admins/mailer", passwords: "admins/passwords", shared: "admins/shared", unlocks: "admins/unlocks"}
  devise_for :doctors, path: 'doctors', controllers: {sessions: "doctors/sessions", registrations:"doctors/registrations", confirmations: "doctors/confirmations", mailer: "doctors/mailer", passwords: "doctors/passwords", shared: "doctors/shared", unlocks: "doctors/unlocks"}
  devise_for :clients, path: 'clients', controllers: {sessions: "clients/sessions", registrations:"clients/registrations", confirmations: "clients/confirmations", mailer: "clients/mailer", passwords: "clients/passwords", shared: "clients/shared", unlocks: "clients/unlocks"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/pick_date' => 'reservations#pick_date'
  get '/pick_date_to_edit' => 'reservations#pick_date_to_edit'

  get '/client' => 'clients#mostrar'
  get '/client/history' => 'clients#history'
  post 'reservations/go_new'
  get '/doctor' => 'doctors#mostrar'
  
  get '/treatments/show' => 'treatments#show'
  get '/treatments/client' => 'treatments#client'
  get '/showclient' => 'treatments#showclient'

  get '/reservations_to_edit' => 'reservations#index_to_edit'
  post '/reservations_go_edit' => 'reservations#go_edit'
  get '/reservations_admin_edit' => 'reservations#admin_edit'

  get '/admin/new_doctor' => 'admins#new_doctor'
  post 'admins/add_doc'
  get '/doctor/history' => 'doctors#history'



end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
  <a class="navbar-brand" href="/">KineTime</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="/">Inicio |<span class="sr-only">(current)</span></a>
      </li>
      <% if doctor_signed_in? %>
          <li class="nav-item active">
          <a class="nav-link" href="/treatments">Tratamientos |<span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item active">
          <a class="nav-link" href="/doctor">Reservas |</a>
          </li>

          <li class="nav-item active">
          <a class="nav-link" href="/doctor/history">Ver Historial |</a>
          </li>

          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Opciones
            <span class="sr-only">(current)</span></a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="/doctors/edit">Editar Perfil</a>
            <a class="dropdown-item"><%= link_to "Cerrar Sesión", destroy_doctor_session_path, method: :delete, :class => 'navbar-link'  %></a>
          </li>
          </div>
          </li>



      <% elsif client_signed_in? %>
        <li class="nav-item active">
          <a class="nav-link" href="/showclient">Tratamientos |<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="/reservations">Reservar Hora |</a>
        </li>
        <li class="nav-item active">
        <a class="nav-link" href="/client">Mis Reservas |</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="/client/history">Ver Historial |</a>
          </li>

        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Opciones |
          <span class="sr-only">(current)</span></a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="/clients/edit">Editar Perfil</a>
          <a class="dropdown-item"><%= link_to "Cerrar Sesión", destroy_client_session_path, method: :delete, :class => 'navbar-link'  %></a>
        </li>
        </div>
        </li>


      <% elsif admin_signed_in? %>
        <li class="nav-item active">
        <a class="nav-link" href="/admin/new_doctor">Crear doctor |</a>
        </li>

        <li class="nav-item active">
        <a class="nav-link" href="/reservations_to_edit">Editar reservas</a>
        </li>

        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Opciones
          <span class="sr-only">(current)</span></a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="/admins/edit">Editar Perfil</a>
          <a class="dropdown-item"><%= link_to "Cerrar Sesión", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %></a>
        </li>
        </div>
        </li>

      <% else %>
        <li class="nav-item active">
        <a class="nav-link" href="/clients/sign_in">Ingresar como Cliente |</a>
        </li>
        <li class="nav-item active">
        <a class="nav-link" href="/doctors/sign_in">Ingresar como Doctor |</a>
        </li>
        <li class="nav-item active">
        <a class="nav-link" href="/admins/sign_in">Ingresar como Administrador |</a>
        </li>
        <li class="nav-item active">
        <a class="nav-link" href="/clients/sign_up">Crear Cuenta de Cliente |</a>
        </li>

      <% end %>









      <!-- <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Opciones
          <span class="sr-only">(current)</span></a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">

          <% if doctor_signed_in? %>
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="/doctor">Reservas</a>
            <a class="dropdown-item" href="/doctors/edit">Editar Perfil</a>
            <a class="dropdown-item"><%= link_to "Cerrar Sesión", destroy_doctor_session_path, method: :delete, :class => 'navbar-link'  %></a>

          <% elsif client_signed_in? %>
            <a class="dropdown-item" href="/reservations">Reservar Hora</a>
            <a class="dropdown-item" href="/client">Mis Reservas</a>
            <a class="dropdown-item" href="/clients/edit">Editar Perfil</a>
            <a class="dropdown-item"><%= link_to "Cerrar Sesión", destroy_client_session_path, method: :delete, :class => 'navbar-link'  %></a>

          <% elsif admin_signed_in? %>
            <a class="dropdown-item" href="/reservations_to_edit">Check Reservations</a>
            <a class="dropdown-item" href="/admin/new_doctor">Another action</a>
            <a class="dropdown-item" href="/admins/edit">Editar Perfil</a>
            <a class="dropdown-item"><%= link_to "Cerrar Sesión", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %></a>

          <% else %>
            <a class="dropdown-item" href="/clients/sign_in">Ingresar como Cliente</a>
            <a class="dropdown-item" href="/doctors/sign_in">Ingresar como Doctor</a>
            <a class="dropdown-item" href="/admins/sign_in">Ingresar como Administrador</a>
            <a class="dropdown-item" href="/clients/sign_up">Crear Cuenta de Cliente</a>

          <% end %>  -->
        </div>
      </li>

    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SchedulerTracker</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <style>
    body { padding-top: 70px; }
  </style>
  <body>
  
    <%= render 'layouts/navigation' %>

  	<% if notice %>
  		<p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    


    <%= yield %>


  
  </body>
</html>